### ISSUE TITLE
Migrate navexplorer.com to Hetzner

### ISSUE THREAD

**Issue by HacheNAV** [navcoin/development#15]
- [x] Migrating navexplorer to hetzner (https://github.com/NavExplorer/navexplorer-frontend/issues/110)
- [x] Migrating navpool to hetzner https://github.com/navcoin/navexplorer-frontend/issues/112
- [x] Enable staking on the navexplorer node for the navpool stakers
- [x] Remove voting ui from navpool (https://github.com/NavPool/navpool.com/issues/13)
- [x] Finish the search by cold staking address pr (https://github.com/NavExplorer/navexplorer-frontend/pull/106)

**Comment by mxaddict** [comment]
@HacheNAV Do you need my pub key to add to the server/s ? :)
